version: '3.1'

services:
    mongodb:
        image: mongo
        restart: always
        ports:
            - 2717:2717
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password