version: "3"
services: 
    mysql-db:
        image: mysql:5.7
        container_name: mysql-db
        hostname: mysql-db
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: userpass
            MYSQL_DATABASE: gador
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes: 
            -   ./db:/var/lib/mysql
        ports:
            -   3306:3306
        expose: 
            -   3306
        networks: 
            -   mysql-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        hostname: phpmyadmin
        restart: always
        environment: 
            PMA_HOST: mysql-db
        ports:
            - 8080:80
        depends_on: 
            - mysql-db
        expose:
            - 80
        networks: 
            - mysql-network

networks: 
    mysql-network:
        driver: bridge